# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
v = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
vr = np.arange(10,50)
vr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
vr.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
vr.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sharif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sharif/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sharif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sharif/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sharif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sharif/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sharif/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Sharif/anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [7]:
vr.ndim

1

8. Create a boolean array with all the True values

In [8]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
final_arr = arr2 > arr
final_arr

#OR

np.ones((2,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [9]:
arr = np.array([[1,2,3], [4,5,6]])
arr
#OR
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
#OR
arr = np.arange(1,25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vec = np.arange(1,10)
vec
vec[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nv = np.zeros(10)
nv[4]  = 1
nv

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
iden = np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype = float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1.,2.,3.],
                    [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                    [7.,2.,12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1.,2.,3.],
                    [4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],
                    [7.,2.,12.]])
arr3  = arr2 > arr1
arr3

array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr[arr % 2 == 1]

array([1., 3., 5.])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr % 2 == 1] = -1
arr


array([-1.,  2., -1.,  4., -1.])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
border = np.ones((2,10))
border[::,1:-1:] = 0
border

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1,2,3],
                  
                     [4,5,6],
                  
                     [7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0][0][0:3] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
_2dar = np.arange(10).reshape(2,5)
print(_2dar)
_2dar[1::,]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[5, 6, 7, 8, 9]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
_2dar = np.arange(10).reshape(2,5)
print(_2dar)
_2dar[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
_2dar = np.arange(10).reshape(2,5)
print(_2dar)
_2dar[::,2:3:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
_10ar = np.random.randn(10,10)
print(_10ar)
print("\n")
print("max val: {}".format(np.amax(_10ar)))
print("min val: {}".format(np.amin(_10ar)))

[[-1.27840641e+00 -1.25707094e+00 -3.99615331e-01 -5.85432598e-01
  -2.37029544e-01  7.12106038e-01  3.32739954e-01  6.92938383e-01
  -9.89980384e-01 -2.49737426e+00]
 [-3.16331624e-01 -9.31211523e-01 -1.50115347e+00  3.44150589e-01
  -6.37089004e-01 -1.06333315e+00 -9.56498890e-02  7.86494638e-02
  -7.89398534e-01 -2.34399815e+00]
 [-1.01836965e+00 -1.92187091e-01  1.55264759e+00 -1.38632593e+00
   3.56155464e-01 -2.25450645e+00 -6.00551842e-01 -1.06432503e+00
  -4.98465253e-01 -1.38730419e-01]
 [-2.10337491e-01 -6.60868074e-01  6.85075950e-01 -7.80340099e-01
  -1.19387213e-01  6.23348124e-01 -6.68002535e-02  9.92520832e-02
   3.60161047e-01 -1.52755127e-01]
 [ 1.26537313e-01 -2.94622880e-01 -5.56626179e-01  5.29028465e-01
  -1.01070912e-01  2.34166704e-01  6.53026337e-02  3.15589369e-01
  -2.59802458e-01  1.15993800e+00]
 [-2.36188178e-01  1.85237505e-01  1.29032344e-01 -5.27062754e-01
   3.50372501e-01 -1.77464479e+00 -1.08292330e+00  4.38921789e-01
  -5.31935346e-01 -6.89791364e-03

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b, return_indices=True))
print("\nOR\n")
print(np.searchsorted(a,np.intersect1d(a,b)))

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

OR

[1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)
data[np.where(names != 'Will')]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.49845213 -0.18750498 -1.0736772   0.15357561]
 [-0.65784938 -0.02663547  0.44663762 -1.1980627 ]
 [ 0.57401142 -2.50797459 -0.47286775  0.39465872]
 [-0.39648499  0.08027871  1.04463666  1.52272066]
 [ 0.50130144  0.14155015 -0.64018513 -0.49128701]
 [-1.44925715  0.00447716 -1.34257239 -0.81772039]
 [ 0.77089367 -1.72512245  1.35843122 -0.05108904]]


array([[ 1.49845213, -0.18750498, -1.0736772 ,  0.15357561],
       [-0.65784938, -0.02663547,  0.44663762, -1.1980627 ],
       [-0.39648499,  0.08027871,  1.04463666,  1.52272066],
       [-1.44925715,  0.00447716, -1.34257239, -0.81772039],
       [ 0.77089367, -1.72512245,  1.35843122, -0.05108904]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)
data[np.where((names != 'Will') & (names != 'Joe'))]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.55195647  0.17105503 -0.83897503 -0.74154549]
 [ 0.2615291  -0.30059035  0.65540592  0.89045467]
 [ 1.90118685 -0.34857349  0.48812083 -0.42919159]
 [-1.55139169 -1.04957264  2.4796877  -0.64289615]
 [-1.25931964  1.21035286  1.44959908  0.37216619]
 [-0.53419287 -0.02571536 -1.08857451 -0.33546737]
 [ 0.94808894 -0.08315518 -2.46881966 -1.57645569]]


array([[ 0.55195647,  0.17105503, -0.83897503, -0.74154549],
       [-1.55139169, -1.04957264,  2.4796877 , -0.64289615]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
ar2dh = np.random.uniform(1,15, size = (5,3))
ar2dh

array([[ 4.22107445,  9.7295999 , 14.69098267],
       [ 7.36948741,  4.54264157, 13.68549478],
       [ 4.78995217,  4.74582812, 10.24288261],
       [12.13797277,  7.50412127, 11.00268532],
       [ 1.95640232,  7.46655832,  2.47685776]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
ar3dh = np.random.uniform(1,16, size = (2,2,4))
ar3dh

array([[[10.99208228,  8.7666164 ,  8.82043408,  2.44906755],
        [ 6.10768552, 10.93169162,  8.40756144, 12.65250084]],

       [[ 8.90229717,  7.14268034, 14.9430475 ,  4.14040942],
        [15.44300423,  9.27673442,  5.6706566 ,  5.63661839]]])

33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(ar3dh,2,0)

array([[[10.99208228,  8.90229717],
        [ 6.10768552, 15.44300423]],

       [[ 8.7666164 ,  7.14268034],
        [10.93169162,  9.27673442]],

       [[ 8.82043408, 14.9430475 ],
        [ 8.40756144,  5.6706566 ]],

       [[ 2.44906755,  4.14040942],
        [12.65250084,  5.63661839]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr34 = np.random.uniform(0,1, size = (10))
print(arr34)
arr34 = np.sqrt(arr34)
arr34[np.where(arr34 < 0.5)] = 0
arr34

[0.50079066 0.38256786 0.1478444  0.23014479 0.44132114 0.81721869
 0.80666662 0.83960926 0.68949226 0.89180445]


array([0.70766564, 0.6185207 , 0.        , 0.        , 0.66432006,
       0.90400149, 0.89814621, 0.91630195, 0.83035671, 0.94435399])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
arr35_1 = np.random.uniform(1,10, size = (12))
arr35_2 = np.random.uniform(1,10, size = (12))

print("Arr1: {}".format(arr35_1))
print("Arr2: {}".format(arr35_2))
max_arr35 = np.maximum(arr35_1,arr35_2)
print("\nMax_array: {}".format(max_arr35))

Arr1: [9.39941201 5.90042026 5.58018953 6.77643166 9.61218807 7.27403023
 7.07498572 3.83987897 3.35317779 1.38127283 7.9574605  4.15514923]
Arr2: [9.03232993 3.41489759 4.6125173  5.92346098 4.21674171 1.58190065
 5.40501981 2.33526471 6.52762592 6.37183678 8.69652796 8.04742194]

Max_array: [9.39941201 5.90042026 5.58018953 6.77643166 9.61218807 7.27403023
 7.07498572 3.83987897 6.52762592 6.37183678 8.69652796 8.04742194]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
un_arr = np.unique(names)
un_arr = np.sort(un_arr)
un_arr

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [45]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.delete(a,np.searchsorted(a,np.intersect1d(a,b)))

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [90]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray)
sampleArray = np.delete(sampleArray,1, axis = 1)
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 1)
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [91]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [95]:
arr = np.random.uniform(1,20,size=(5,4))
print(arr)
np.cumsum(arr)

[[ 3.2373464  11.30535213 11.02995316 17.94049267]
 [13.52169884  2.5066504  18.92212745 16.09596729]
 [19.71902956  2.92931229  1.94992014  1.46343021]
 [ 3.15040964  7.50561634  1.79957649  9.5653914 ]
 [16.25928605  4.92819467 18.33666523 17.72604488]]


array([  3.2373464 ,  14.54269853,  25.57265169,  43.51314436,
        57.0348432 ,  59.5414936 ,  78.46362105,  94.55958834,
       114.2786179 , 117.2079302 , 119.15785034, 120.62128054,
       123.77169018, 131.27730653, 133.07688301, 142.64227442,
       158.90156046, 163.82975514, 182.16642037, 199.89246525])