# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [47]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(2,5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [48]:
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)
stk = np.vstack((a,b))
stk

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [49]:
hstk = np.hstack((a,b))
hstk

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [50]:
arr1d = np.arange(10).reshape(2,5)
print(arr1d)
arr2d = arr1d.flatten()
print(arr2d)
print("OR")
arr2d = arr1d.reshape(-1)
arr2d

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
OR


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [51]:
hdarr = np.arange(15).reshape(3,1,5)
print(hdarr)
arr1d = np.ravel(hdarr)
arr1d

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [52]:
dim1arr = np.arange(15)
print(dim1arr)
dim1arr.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [53]:
arr55 = np.arange(25).reshape(5,5)
print(arr55)
np.power(arr55,2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [54]:
arr56 = np.arange(30).reshape(5,6)
print(arr56)
np.mean(arr56)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [55]:
np.std(arr56)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [56]:
np.median(arr56)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [57]:
print(arr56.T)
print("OR")
np.transpose(arr56)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
OR


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [58]:
arr4x4 = np.arange(16).reshape(4,4)
print(arr4x4)
print("Sum of Diagonal elements: {}".format(np.trace(arr4x4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of Diagonal elements: 30


## Question:13

### Find the determinant of the previous array in Q12?

In [61]:
print(arr4x4)
np.linalg.det(arr4x4)
print("Determinant of Matrix: {}".format(np.linalg.det(arr4x4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [63]:
print("5th Percentile: {}".format(np.percentile(arr4x4,5)))
print("95th Percentile: {}".format(np.percentile(arr4x4,95)))

5th Percentile: 0.75
95th Percentile: 14.25


## Question:15

### How to find if a given array has any null values?

In [66]:
np.isnan(arr4x4).any()

False